// Generated by dts-bundle-generator v9.5.1

export type Store = {
	get: (key: string) => Promise<unknown>;
	set: (key: string, value: unknown, options?: unknown) => Promise<unknown>;
	del: (key: string) => Promise<unknown>;
	has?: (key: string) => Promise<boolean>;
	clear?: () => Promise<unknown>;
};
type Headers$1 = {
	[name: string]: string;
};
export type Query = {
	[name: string]: string;
};
export type Methods = "get" | "head" | "post" | "patch" | "put" | "delete" | "GET" | "HEAD" | "POST" | "PATCH" | "PUT" | "DELETE";
type Body$1 = string | unknown[] | {
	[key: string]: unknown;
} | FormData | HTMLFormElement | SubmitEvent | ReadableStream;
export type FchError = Error & {
	response?: Response;
};
export type FchRequest = Omit<RequestInit, "body" | "headers" | "method"> & {
	url: string;
	method: string;
	headers: Headers$1;
	body?: string | FormData | ReadableStream | null;
};
export type FchResponse = {
	status: number;
	statusText: string;
	headers: Headers$1;
	body: unknown;
};
export type Options = Omit<RequestInit, "body" | "cache" | "headers" | "method"> & {
	url?: string;
	method?: Methods;
	query?: Query;
	headers?: Headers$1;
	baseUrl?: string;
	baseURL?: string;
	body?: Body$1;
	cache?: Store;
	output?: string;
	before?: (req: FchRequest) => FchRequest | Promise<FchRequest>;
	after?: (res: FchResponse) => FchResponse | Promise<FchResponse>;
	error?: (error: FchError) => any;
};
export interface FchInstance {
	<T = any>(url?: string, options?: Options): Promise<T>;
	create: (options?: Options) => FchInstance;
	get: <T = any>(url: string, options?: Options) => Promise<T>;
	head: <T = any>(url: string, options?: Options) => Promise<T>;
	post: <T = any>(url: string, body?: Body$1, options?: Options) => Promise<T>;
	patch: <T = any>(url: string, body?: Body$1, options?: Options) => Promise<T>;
	put: <T = any>(url: string, body?: Body$1, options?: Options) => Promise<T>;
	delete: <T = any>(url: string, options?: Options) => Promise<T>;
	del: <T = any>(url: string, options?: Options) => Promise<T>;
	text: () => Promise<string>;
	json: <T = any>() => Promise<T>;
	blob: () => Promise<Blob>;
	stream: () => ReadableStream | null;
	arrayBuffer: () => Promise<ArrayBuffer>;
	formData: () => Promise<FormData>;
	body: <T = any>() => Promise<T>;
	clone: () => Response;
	raw: () => Response;
	response: <T = any>() => Promise<T>;
	url: string;
	method: Methods;
	query: Query;
	headers: Headers$1;
	baseUrl: string | null;
	baseURL: string | null;
	cache?: Store;
	output: string;
	credentials: RequestCredentials;
	before?: (req: FchRequest) => FchRequest | Promise<FchRequest>;
	after?: (res: FchResponse) => FchResponse | Promise<FchResponse>;
	error?: (error: FchError) => any;
}
export declare function create(defaults?: Options): FchInstance;
declare const _default: FchInstance;

export {
	_default as default,
};

export {};
